Repository bounswe/bounswe2022group5, pull requests merged in 2022-05, with the labels that each got.

#77 Created Read me for practice-app.
  practice_app/README.md
Labels: Type: Documentation

#82 User APIs are initially implemented
  practice-app/practice_app/urls.py
  practice-app/user/serializers.py
  practice-app/user/urls.py
  practice-app/user/views.py
Labels: High Priority, Type: To Do, Status: Need Review

#89 User API bugs are fixed
  practice-app/user/urls.py
  practice-app/user/views.py
Labels: Type: Bug, High Priority, Status: Need Review

#92 Practice app/feature/post #83
  practice-app/post/models.py
  practice-app/post/serializers.py
  practice-app/post/urls.py
  practice-app/post/views.py
Labels: Medium Priority, Status: Need Review

#91 Practice app/feature/comment #86
  practice-app/comment/serializers.py
  practice-app/comment/urls.py
  practice-app/comment/views.py
  practice-app/practice_app/urls.py
  practice-app/requirements.txt
Labels: High Priority, Type: To Do, Status: Need Review

#98 Practice-app/feature/post-info creation of the API enpoint
  practice-app/post_info/__pycache__/__init__.cpython-310.pyc
  practice-app/post_info/__pycache__/admin.cpython-310.pyc
  practice-app/post_info/__pycache__/apps.cpython-310.pyc
  practice-app/post_info/__pycache__/forms.cpython-310.pyc
  practice-app/post_info/__pycache__/serializers.cpython-310.pyc
  practice-app/post_info/__pycache__/urls.cpython-310.pyc
  practice-app/post_info/__pycache__/views.cpython-310.pyc
  practice-app/post_info/forms.py
  practice-app/post_info/serializers.py
  practice-app/post_info/templates/PostInfo.html
  practice-app/post_info/templates/forms.html
  practice-app/post_info/templates/view.html
  practice-app/post_info/urls.py
  practice-app/post_info/views.py
Labels: High Priority, Status: Accepted

#103 Practice app/enhancement/user #87
  practice-app/practice_app/settings.py
  practice-app/requirements.txt
  practice-app/user/static/style.css
  practice-app/user/static/style2.css
  practice-app/user/templates/allUsers.html
  practice-app/user/templates/user.html
  practice-app/user/urls.py
  practice-app/user/views.py
Labels: High Priority, Type: Enhancement, Status: Need Review

#99 Practice app/feature/post #83
  practice-app/post/forms.py
  practice-app/post/models.py
  practice-app/post/static/404.css
  practice-app/post/static/index.css
  practice-app/post/static/references.txt
  practice-app/post/static/table.css
  practice-app/post/templates/base.html
  practice-app/post/templates/create.html
  practice-app/post/templates/get.html
  practice-app/post/templates/index.html
  practice-app/post/templates/notfound.html
  practice-app/post/tests/__init__.py
  practice-app/post/tests/test_forms.py
  practice-app/post/tests/test_models.py
  practice-app/post/tests/test_urls.py
  practice-app/post/tests/test_views.py
  practice-app/post/urls.py
  practice-app/post/views.py
Labels: High Priority, Status: Need Review

#106 Practice app/feature/post #102
  practice-app/post/forms.py
  practice-app/post/static/cards.css
  practice-app/post/static/index.css
  practice-app/post/static/references.txt
  practice-app/post/templates/base.html
  practice-app/post/templates/create.html
  practice-app/post/templates/get.html
  practice-app/post/views.py
Labels: Status: In Progress, Status: Need Review, Urgent Priority

#114 Bug fixed related misdirecting url
  practice-app/category/templates/base_category.html
  practice-app/category/templates/createForm_category.html
  practice-app/category/templates/index_category.html
  practice-app/category/templates/listCategories_category.html
  practice-app/category/views.py
  practice-app/practice_app/urls.py
Labels: High Priority

#110 Practice app/feature/comment info #84
  practice-app/comment_info/static/errorStyle.css
  practice-app/comment_info/static/resultStyle.css
  practice-app/comment_info/static/style.css
  practice-app/comment_info/templates/error.html
  practice-app/comment_info/templates/index.html
  practice-app/comment_info/templates/result.html
  practice-app/comment_info/tests.py
  practice-app/comment_info/urls.py
  practice-app/comment_info/views.py
Labels: High Priority, Status: Need Review

#123 bug-fix/misdirecting post url
  practice-app/post/static/boun.jpg
  practice-app/post/static/post_404.css
  practice-app/post/static/post_cards.css
  practice-app/post/static/post_index.css
  practice-app/post/templates/post_base.html
  practice-app/post/templates/post_create.html
  practice-app/post/templates/post_get.html
  practice-app/post/templates/post_index.html
  practice-app/post/templates/post_notfound.html
  practice-app/post/tests.py
  practice-app/post/views.py
Labels: Low Priority, Status: Need Review

#127 Practice app/enhancement/login #121
  practice-app/_main/static/styleLogin.css
  practice-app/_main/static/styleMain.css
  practice-app/_main/templates/HomePage.html
  practice-app/_main/templates/login.html
  practice-app/_main/urls.py
  practice-app/_main/views.py
  practice-app/practice_app/settings.py
  practice-app/practice_app/urls.py
  practice-app/user/static/styleUser.css
  practice-app/user/static/styleUser2.css
  practice-app/user/templates/allUsers.html
  practice-app/user/templates/user.html
  practice-app/user/tests/test_urls.py
  practice-app/user/urls.py
Labels: High Priority, Type: Enhancement, Status: Need Review

#125 Practice-app/feature/article-info #97-2
  practice-app/article_info/forms.py
  practice-app/article_info/templates/error_article_info.html
  practice-app/article_info/templates/forms_article_info.html
  practice-app/article_info/templates/updated_article_info.html
  practice-app/article_info/templates/view_article_info.html
  practice-app/article_info/urls.py
  practice-app/article_info/views.py
Labels: High Priority, Status: Need Review

#129 Practice app/feature/article-#105
  practice-app/article/forms.py
  practice-app/article/urls.py
  practice-app/article/views.py
Labels: High Priority, Type: Enhancement, Status: Need Review

#130 Improvements in the Comment Frontend
  practice-app/comment/forms.py
  practice-app/comment/serializers.py
  practice-app/comment/templates/comment.html
  practice-app/comment/templates/listComments.html
  practice-app/comment/urls.py
  practice-app/comment/views.py
Labels: Medium Priority, Type: Enhancement, Status: Need Review

#136 Redirection problems, test-case updates and a new feature
  practice-app/post/forms.py
  practice-app/post/static/post_index.css
  practice-app/post/static/table.css
  practice-app/post/templates/post_base.html
  practice-app/post/templates/post_create.html
  practice-app/post/templates/post_get.html
  practice-app/post/templates/post_notfound.html
  practice-app/post/tests/test_forms.py
  practice-app/post/tests/test_urls.py
  practice-app/post/tests/test_views.py
  practice-app/post/urls.py
  practice-app/post/views.py
Labels: Medium Priority, Type: Enhancement, Status: Need Review

#132 Practice app/testing/article-info #108
  practice-app/article_info/forms.py
  practice-app/article_info/templates/updated_article_info.html
  practice-app/article_info/templates/view_article_info.html
  practice-app/article_info/tests.py
  practice-app/article_info/tests/__init__.py
  practice-app/article_info/tests/test_forms.py
  practice-app/article_info/tests/test_urls.py
  practice-app/article_info/tests/test_views.py
  practice-app/article_info/urls.py
  practice-app/article_info/views.py
Labels: Medium Priority, Type: Testing, Status: Need Review

#133 Practice app/feature/rate comment
  practice-app/practice_app/urls.py
  practice-app/rate_comment/forms.py
  practice-app/rate_comment/serializers.py
  practice-app/rate_comment/templates/formsratecomment.html
  practice-app/rate_comment/templates/viewratecomment.html
  practice-app/rate_comment/urls.py
  practice-app/rate_comment/views.py
Labels: High Priority, Type: To Do, Status: Need Review

#139 Bug-Fix on the external API
  practice-app/post/forms.py
  practice-app/post/static/boun.jpg
  practice-app/post/templates/post_base.html
  practice-app/post/tests/test_forms.py
  practice-app/post/tests/test_models.py
  practice-app/post/tests/test_urls.py
  practice-app/post/tests/test_views.py
  practice-app/post/views.py
Labels: Medium Priority, Status: Need Review

#131 Unit Tests for the Comment Endpoint
  practice-app/comment/tests.py
  practice-app/comment/tests/__init__.py
  practice-app/comment/tests/test_forms.py
  practice-app/comment/tests/test_models.py
  practice-app/comment/tests/test_urls.py
  practice-app/comment/tests/test_views.py
  practice-app/comment/views.py
Labels: Medium Priority, Type: Testing, Status: Need Review

#141 url direction of back and home page buttons changed to generalize
  practice-app/post/templates/post_base.html
  practice-app/post/templates/post_create.html
  practice-app/post/templates/post_get.html
  practice-app/post/templates/post_notfound.html
Labels: High Priority, Status: Need Review

#146 Practice-App/bug-fix/article-info-#144
  practice-app/article_info/templates/error_article_info.html
  practice-app/article_info/templates/forms_article_info.html
  practice-app/article_info/templates/updated_article_info.html
  practice-app/article_info/templates/view_article_info.html
Labels: Type: Bug, High Priority, Status: Need Review

#150 Last changes for Practice App
  practice-app/_main/templates/login.html
  practice-app/user/templates/user.html
  practice-app/user/tests/test_views.py
  practice-app/user/views.py
Labels: High Priority, Type: Enhancement, Status: Need Review

#153 Fixing bugs related to migrations and removing unnecessary files
  practice-app/_main/admin.py
  practice-app/_main/migrations/__init__.py
  practice-app/_main/models.py
  practice-app/_main/tests.py
  practice-app/article/migrations/0001_initial.py
  practice-app/article_info/admin.py
  practice-app/article_info/migrations/__init__.py
  practice-app/category/migrations/0001_initial.py
  practice-app/category_info/admin.py
  practice-app/category_info/migrations/__init__.py
  practice-app/comment/migrations/0001_initial.py
  practice-app/comment/migrations/0002_comment_nofdownvotes_comment_nofupvotes.py
  practice-app/comment/migrations/0003_rename_nofdownvotes_comment_nof_downvotes_and_more.py
  practice-app/comment_info/admin.py
  practice-app/comment_info/migrations/__init__.py
  practice-app/post/migrations/0001_initial.py
  practice-app/post/migrations/0002_alter_post_covid19cases.py
  practice-app/post/migrations/0002_alter_post_covid19cases_alter_post_timestamp.py
  practice-app/post/migrations/0003_merge_20220516_1926.py
  practice-app/post_info/admin.py
  practice-app/post_info/migrations/__init__.py
  practice-app/post_info/migrations/__pycache__/__init__.cpython-310.pyc
  practice-app/rate_article/migrations/__init__.py
  practice-app/rate_comment/admin.py
  practice-app/rate_comment/migrations/__init__.py
  practice-app/rate_comment/views.py
  practice-app/rate_post/admin.py
  practice-app/rate_post/migrations/__init__.py
  practice-app/user/admin.py
  practice-app/user/migrations/__init__.py
  practice-app/user/models.py
Labels: Type: Bug, Medium Priority, Status: Need Review

#151 Rate article
  practice-app/practice_app/urls.py
  practice-app/rate_article/forms.py
  practice-app/rate_article/serializers.py
  practice-app/rate_article/templates/forms_rate_article.html
  practice-app/rate_article/templates/view_rate_article.html
  practice-app/rate_article/tests/test_forms.py
  practice-app/rate_article/tests/test_urls.py
  practice-app/rate_article/tests/test_views.py
  practice-app/rate_article/urls.py
  practice-app/rate_article/views.py
Labels: High Priority, Status: Need Review

#157 Bug fixed for conflicted URLs
  practice-app/rate_comment/templates/formsratecomment.html
  practice-app/rate_comment/urls.py
  practice-app/rate_comment/views.py
Labels: Type: Bug, High Priority, Status: Need Review

#159 case-insensitive property fixed, final adjustments before deployment
  practice-app/post/templates/post_get.html
  practice-app/post/views.py
Labels: Medium Priority, Status: Need Review

#160 Practice app/testing/rate comment #134
  practice-app/post/templates/post_create.html
  practice-app/post/templates/post_get.html
  practice-app/practice_app/urls.py
  practice-app/rate_comment/tests/__init__.py
  practice-app/rate_comment/tests/test_forms.py
  practice-app/rate_comment/tests/test_urls.py
  practice-app/rate_comment/tests/test_views.py
Labels: High Priority, Type: Testing, Status: Need Review

#165 Practice-app: Bug-fix for tests of post-info
  practice-app/post_info/templates/forms.html
  practice-app/post_info/tests/test_urls.py
  practice-app/post_info/tests/test_views.py
  practice-app/post_info/urls.py
Labels: Type: Bug, High Priority, Status: Need Review

#167 Fixed Some Bugs Related to Tests
  practice-app/category/views.py
  practice-app/rate_article/tests.py
  practice-app/rate_article/tests/__init__.py
  practice-app/rate_article/urls.py
  practice-app/rate_comment/urls.py
  practice-app/rate_post/tests.py
  practice-app/rate_post/urls.py
  practice-app/user/tests/test_views.py
  practice-app/user/views.py
Labels: Type: Bug, High Priority, Status: Need Review
